FROM node:22-alpine AS base
WORKDIR /app
RUN corepack enable

FROM base AS deps
RUN apk add --no-cache openssl
COPY package.json pnpm-lock.yaml* pnpm-workspace.yaml ./
COPY apps/api/package.json apps/api/package.json
COPY packages/shared/package.json packages/shared/package.json
COPY packages/protocol/package.json packages/protocol/package.json
RUN pnpm install --frozen-lockfile=false

FROM deps AS build
COPY . .
RUN pnpm --filter @gateway/shared build
RUN pnpm --filter @gateway/protocol build
RUN pnpm --filter @gateway/api prisma:generate
RUN pnpm --filter @gateway/api build

FROM node:22-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production
RUN corepack enable
RUN apk add --no-cache openssl
RUN mkdir -p /app/data
COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/apps/api/node_modules ./apps/api/node_modules
COPY --from=deps /app/packages ./packages
COPY --from=build /app/node_modules/.pnpm/@prisma+client@5.16.2_prisma@5.16.2/node_modules/.prisma ./node_modules/.pnpm/@prisma+client@5.16.2_prisma@5.16.2/node_modules/.prisma
COPY --from=build /app/apps/api/dist ./apps/api/dist
COPY apps/api/prisma ./apps/api/prisma
COPY apps/api/scripts ./apps/api/scripts
COPY apps/api/package.json ./apps/api/package.json
COPY infra/docker/api-entrypoint.sh ./infra/docker/api-entrypoint.sh
RUN chmod +x ./infra/docker/api-entrypoint.sh
EXPOSE 3000
ENTRYPOINT ["./infra/docker/api-entrypoint.sh"]
CMD ["node", "apps/api/dist/main.js"]
